# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies without running scripts to avoid potential issues
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project and ensure the main file is executable
RUN npm run build

# Expose any ports if needed (not required for this MCP as it uses stdio)

# Default command to run the MCP server
CMD [ "node", "build/index.js" ]
